prometheusOperator:
  createCustomResourceBindings: false
  rbac:
    create: true
    useClusterRole: false
  namespaces:
    releaseNamespace: true
  admissionWebhooks:
    enabled: false

prometheus:
  rbac:
    create: true
    useClusterRole: false
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        monitoring: "true"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  rbac:
    create: true
    namespaced: true
  persistence:
    enabled: true
    size: 2Gi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards/providers

nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false
kubeStateMetrics:
  enabled: false
kube-state-metrics:
  enabled: false
  rbac:
    create: false
    useClusterRole: false
